### ISSUE TITLE
ecdsa-01 and ecdsa-02 have changed from cose_sign1 to cose_sign.

### ISSUE THREAD

**Issue by mcr** [cose-wg/Examples#85]
A previous version of this repo had ecdsa-01 (or probably -02) using cose_sign1.
The latest version is using cose_sign, which moves the algorithm identifiers into the array[4], rather than the global protected bucket.  Bad on my code for not handling both, but I wanted to make sure that the change was intentional, and query whether there are any cose_sign1 examples.

**Comment by jimsch** [comment]
The ecdsa-sig-* examples are still sign1 examples.

**Comment by mcr** [comment]
Jim Schaad <notifications@github.com> wrote:
    > The ecdsa-sig-* examples are still sign1 examples.

so the change is intentional :-)


-- 
]               Never tell me the odds!                 | ipv6 mesh networks [ 
]   Michael Richardson, Sandelman Software Works        | network architect  [ 
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by jimsch** [comment]
Yes - it was intentional.  This mirrors the other directories.  You can easily distinguish between them as there is a JSON key of sign vs sign1
