### ISSUE TITLE
Label for "kid" in encryption examples is wrong

### ISSUE THREAD

**Issue by thiagomacieira** [cose-wg/Examples#86]
In the following example, the unprotected map has two items, the "alg" and "kid":
https://github.com/cose-wg/Examples/blob/892673f8faba75eb4ff8ca7b9507c1455ecb7425/encrypted-tests/enc-pass-01.json#L17-L20

But in the encoded data, we find label 5:

https://github.com/cose-wg/Examples/blob/892673f8faba75eb4ff8ca7b9507c1455ecb7425/encrypted-tests/enc-pass-01.json#L40

According to https://www.iana.org/assignments/cose/cose.xhtml#header-parameters, "kid" is 4 and "IV" is 5.

**Comment by thiagomacieira** [comment]
Never mind, looks like sending IV here was intentional. I just don't know where the KID went.

**Comment by jimsch** [comment]
The unprotected is being pulled from line 6 not from line 17.  I should remove the lines 17-20.
