### ISSUE TITLE
RSA-PSS examples using correct salt length?

### ISSUE THREAD

**Issue by grzuy** [cose-wg/Examples#91]
Hi,

When attempting to verify RSA-PSS example I am not able to verify correctly if enforcing the salt length in https://tools.ietf.org/html/rfc8230#section-2. E.g. 32 for PS256.

It does verify correctly if I let the salt length be calculated automatically based on the signature.

Am I missing something here?

Thank you.

**Comment by jimsch** [comment]
I don't know,   In my code I am passing in the byte length of the digest for the length of the salt.  This should produce the same set of values values as provided in the table for RFC 8230.  For my crypto code I am currently using the C# versions of BouncyCastle.  I have not put it support for my Java or C libraries as I don't know how common RSA is going to be for the IoT world and it was very low priority.  I can push up the priority for the Java library to double check things. 

If public a pointer to your code might let me find something

**Comment by grzuy** [comment]
This is the piece that's not working for me https://github.com/cedarcode/cose-ruby/blob/pss/lib/cose/signature_verifier/pss.rb#L14. It's calling `#verify_pss` on an [`OpenSSL::PKey::RSA`](https://ruby-doc.org/stdlib-2.6.4/libdoc/openssl/rdoc/OpenSSL/PKey/RSA.html) instance.

See I'm using `salt_length: :digest`. And have tests failing for the 3 examples https://travis-ci.org/cedarcode/cose-ruby/jobs/579249216.

Note that I get passes if I either use `salt_length: :auto` or manually force it to use:
- `salt_length: 64` for "RSA-PSS w/ SHA-256"
- `salt_length: 128` for "RSA-PSS w/ SHA-384"
- `salt_length: 128` for "RSA-PSS w/ SHA-512"

Thank you!

**Comment by jimsch** [comment]
Cute - You are totally correct.  My code is wrong.  It should be passing in the length in bits not the length in bytes.

**Comment by jimsch** [comment]
Should be fixed now

**Comment by grzuy** [comment]
Great. Works now!

Thank you for the quick fix.
