### ISSUE TITLE
eddsa-sig-02.json `kid` doesn't match

### ISSUE THREAD

**Issue by bdewater** [cose-wg/Examples#95]
Heya,

I'm running into an issue where the decoded CBOR for the "EdDSA-sig-02: EdDSA - 448 - sign1" example contains `"kid":"3d448"` while the actual `kid` is: https://github.com/cose-wg/Examples/blob/679300afff653f09761cba5da25cdd7ab1882180/eddsa-examples/eddsa-sig-02.json#L6-L8

The signature verifies successfully if I ignore the `kid` mismatch, so the key seems to be otherwise correct?

**Comment by jimsch** [comment]
Yes the keys are correct, this is a typo that does not affect any of the crypto code itself.  It would cause problems if you are identifying keys from the value so it does need to get fixed.

**Comment by jimsch** [comment]
Fixed by #96

**Comment by bdewater** [comment]
Nice! Thank you for maintaining this, it's very useful.
